name: scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "17 4 * * 1"
  push:
    branches: [master, main]

permissions: {}

jobs:
  analysis:
    name: OSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: scorecard-results.sarif
          retention-days: 7

      - name: Upload SARIF to code-scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: scorecard-results.sarif
          category: scorecard
